# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
sudo: false
cache: packages

addons:
  apt:
    packages:
      - valgrind
      - tcl8.5-dev
      - tk8.5-dev

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

warnings_are_errors: false
r_build_args: "--no-build-vignettes"
r_check_args: "--as-cran --no-manual --run-donttest"

#r_check_args: "--as-cran --run-donttest --use-valgrind"
#env:
#  - VALGRIND_OPTS="--leak-check=full --track-origins=yes"
#
#script:
#  - |
#    travis_wait 42 R CMD build . --no-build-vignettes
#    travis_wait 59 R CMD check MSEtool*tar.gz --as-cran --use-valgrind
